version: '3.4'

services:
  portfoliowebsite:
    image: portfoliowebsite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
